#!/usr/bin/env ruby
usage = <<~EOF
  ruby-test-watcher /path/to/directory
EOF

directory = ARGV[0]
$stderr.write usage and exit(1) unless directory
directory = directory.gsub('^~', "#{Dir.home}")
$stderr.write usage and exit(1) unless File.exist? directory

exec "cd #{File.expand_path File.dirname(__FILE__)} && bundle exec ruby-test-watcher.rb #{directory}"
